---
title: "Homework 3"
author: Tu  Nguyen
output: github_document
---

This is my solution to HW2.


```{r setup, include = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Problem 2

Tidy data into "minute of the day" and "activity count" columns

```{r}
accel_df = 
  read_csv("./data/accel_data.csv") %>% 
   pivot_longer(
    activity.1:activity.1440,
    names_to = "minute",
    names_prefix = "activity.",
    values_to = "activity_count"
  ) %>% 
  mutate(
    weekday_or_weekend =
      recode(day,
             "Monday" = "weekday",
             "Tuesday" = "weekday",
             "Wednesday" = "weekday",
             "Thursday" = "weekday",
             "Friday" = "weekday",
             "Saturday" = "weekend",
             "Sunday" = "weekend")
  )
```

There are 6 variables which include `week`, `day_id`, `day`, `minute of the day`, `activity_count`, and `weekday_or_weekend`. There are total 50,400 observations. 


```{r}
accel_df_tidy = 
  accel_df %>% 
  group_by(week,day_id, day) %>% 
  summarise(
    mean_activity_count = mean(activity_count, na.rm = TRUE)
  ) %>% 
  pivot_wider(
    names_from = day,
    values_from = mean_activity_count
  )
```

Patient's activity count is high on the weekends during the first 3 weeks. In general, patient is more active during the weekdays. 

